// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace unity
{
public static class zombiecross
{
        public const string achievement_first_death = "CgkIq6GznYALEAIQBw"; // <GPGSID>
        public const string achievement_first_buy = "CgkIq6GznYALEAIQDQ"; // <GPGSID>
        public const string leaderboard_hall_of_fame = "CgkIq6GznYALEAIQAA"; // <GPGSID>
        public const string package_name = "unity.zombiecross"; // <GPGSID>
        public const string achievement_sergeant = "CgkIq6GznYALEAIQCQ"; // <GPGSID>
        public const string achievement_first_burn = "CgkIq6GznYALEAIQDA"; // <GPGSID>
        public const string leaderboard_multiplayer_of_fame = "CgkIq6GznYALEAIQAQ"; // <GPGSID>
        public const string achievement_first_drown = "CgkIq6GznYALEAIQCA"; // <GPGSID>
        public const string achievement_first_frontflip = "CgkIq6GznYALEAIQBA"; // <GPGSID>
        public const string achievement_first_backflip = "CgkIq6GznYALEAIQAg"; // <GPGSID>
        public const string achievement_first_explotion = "CgkIq6GznYALEAIQBg"; // <GPGSID>
        public const string achievement_two_backflip = "CgkIq6GznYALEAIQAw"; // <GPGSID>
        public const string achievement_two_frontflip = "CgkIq6GznYALEAIQBQ"; // <GPGSID>
        public const string achievement_first_freeze = "CgkIq6GznYALEAIQDg"; // <GPGSID>
        public const string achievement_veteran = "CgkIq6GznYALEAIQCw"; // <GPGSID>
        public const string achievement_assassin = "CgkIq6GznYALEAIQCg"; // <GPGSID>

}
}
